# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='my location default', max_length=120),
        ),
    ]
